# Generated by Django 5.0.1 on 2024-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=155, verbose_name='Кол-во наград')),
                ('project', models.CharField(max_length=155, verbose_name='Завершенные проекты')),
                ('review', models.CharField(max_length=155, verbose_name='кол-во отзывов')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
