# Generated by Django 5.0.1 on 2024-01-30 13:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='award',
            field=ckeditor.fields.RichTextField(verbose_name='Кол-во наград'),
        ),
        migrations.AlterField(
            model_name='data',
            name='project',
            field=ckeditor.fields.RichTextField(verbose_name='Завершенные проекты'),
        ),
        migrations.AlterField(
            model_name='data',
            name='review',
            field=ckeditor.fields.RichTextField(verbose_name='кол-во отзывов'),
        ),
    ]
