# Generated by Django 5.0.1 on 2024-01-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
